### PR TITLE
fix: include app_id in patch storage path

### LINKED ISSUE #3174: fix: patch path to include app_id
**Description**

When developing with Shorebird it's possible to have an two different apps with the same bundle identifier being run locally which can cause old patch artifacts to be applied to a new app

**Steps To Reproduce**

1. `shorebird init`
2. `shorebird release macos`
3. Change something small
4. `shorebird patch macos`
5. `shorebird preview`
6. Observe the patch being applied.
7. `shorebird init --force` (create a new app)
8. `shorebird preview`
9. Observe the old patch being applied to the new app

**Expected Behavior**

I'd expect the old patch to not apply since the app_id has changed.

**Screenshots**

```txt
(FlutterMacOS) [shorebird] ConfigureShorebird success!
(FlutterMacOS) [shorebird] patchPath: /Users/felix/Library/Containers/com.example.example/Data/Library/Application Support/shorebird/shorebird_updater/patches/3/dlc.vmcode
[dev.shorebird:updater::network] [shorebird] Sending patch check request: PatchCheckRequest { app_id: "48e6e764-96ee-4bcd-aa8b-e71ae060b8df", channel: "stable", release_version: "2.0.0+1", platform: "macos", arch: "aarch64" }
[dev.shorebird:updater::updater] [shorebird] Reporting successful launch.
[dev.shorebird:updater::cache::patch_manager] [shorebird] Deleting patch artifacts older than 3
[dev.shorebird:updater::updater] [shorebird] Patch check response: PatchCheckResponse { patch_available: true, patch: Some(Patch { number: 1, hash: "78861dd2c622dbb839ead444a0935f3e246cfe47916d0e1993c136dc11929679", download_url: "https://cdn.shorebird.cloud/api/v1/patches/48e6e764-96ee-4bcd-aa8b-e71ae060b8df/macos/aarch64/220379/dlc.vmcode", hash_signature: None }), rolled_back_patch_numbers: Some([]) }
[dev.shorebird:updater::cache::patch_manager] [shorebird] No public key provided, skipping signature verification
2025-06-16 12:27:53.447 Df example[13428:392bd5] [dev.shorebird:updater::network] [shorebird] Downloading patch from: https://cdn.shorebird.cloud/api/v1/patches/48e6e764-96ee-4bcd-aa8b-e71ae060b8df/macos/aarch64/220379/dlc.vmcode
[dev.shorebird:updater::network] [shorebird] Writing patch to: "/Users/felix/Library/Containers/com.example.example/Data/Library/Application Support/shorebird/shorebird_updater/downloads/1"
[dev.shorebird:updater::network] [shorebird] Wrote patch to: "/Users/felix/Library/Containers/com.example.example/Data/Library/Application Support/shorebird/shorebird_updater/downloads/1"
[dev.shorebird:updater::updater] [shorebird] Inflating patch from "/Users/felix/Library/Containers/com.example.example/Data/Library/Application Support/shorebird/shorebird_updater/downloads/1"
[dev.shorebird:updater::updater] [shorebird] Patch successfully applied to "/Users/felix/Library/Containers/com.example.example/Data/Library/Application Support/shorebird/shorebird_updater/downloads/1.full"
[dev.shorebird:updater::updater] [shorebird] Patch 1 successfully downloaded. It will be launched when the app next restarts.
[dev.shorebird:updater::updater] [shorebird] Update thread finished with status: Update installed
[dev.shorebird:updater::network] [shorebird] Sending patch check request: PatchCheckRequest { app_id: "48e6e764-96ee-4bcd-aa8b-e71ae060b8df", channel: "stable", release_version: "2.0.0+1", platform: "macos", arch: "aarch64" }
[dev.shorebird:updater::cache::patch_manager] [shorebird] No public key provided, skipping signature verification
2025-06-16 12:28:01.602 Df example[13428:392bec] [dev.shorebird:updater::updater] [shorebird] Patch 1 is already installed, skipping.
[dev.shorebird:updater::cache::patch_manager] [shorebird] No public key provided, skipping signature verification
```

### PR DESCRIPTION
**Pull request by bryanoltman**
Include app_id in the patch cache path to avoid collisions. This is only necessary on desktop platforms, as mobile apps are sandboxed.

Fixes https://github.com/shorebirdtech/shorebird/issues/3174

### CODE REVIEW

File: engine/src/flutter/shell/common/shorebird/shorebird.cc [hunk 1]
```diff
@@ -86,10 +86,30 @@ bool ConfigureShorebird(const ShorebirdConfigArgs& args,
   patch_path = args.release_app_library_path;
   auto shorebird_updater_dir_name = "shorebird_updater";
 
+  // Parse app id from shorebird.yaml
```
Comment (eseidel) [inline engine/src/flutter/shell/common/shorebird/shorebird.cc]: I would split this out and write a brief unittest for it.  shorebird_test.cc should exist and can be used.

string ReadYamlKey(string yaml);

Comment (bryanoltman) [reply engine/src/flutter/shell/common/shorebird/shorebird.cc]: Done

**Review by eseidel — APPROVED** [review]
